ROUTINE CriarLogMensgem

 
 Set pDataInicio = ##class(%UTC).NowLocal()
 Set pDataInicio = "24/06/2026 15:36:26"
 Set pStatus = 1
 Set pClasse = "LogMensagem"
 Set pMetodo = "LogMetodo"
 Set pStatusProcesso = "Processo realizado com sucesso!" 
 Set pStatusCode = "1"
 Set pLastId =5
 Set pPageSize = 10
 Set pDataFim = $ZDateTime($HOROLOG,4)
 Set jsonArray = ##class(%DynamicArray).%New()
 set teste = ..%ClassName()
 Set teste1 = $ZNAME

 Set IdLog = 4 
  
 
 Set LogMensagemCriar = ##class(Treinamento.Data.LogMensagem).CriarEntrada("pMetodo", "pClasse")
 Set IdLog  = LogMensagemCriar.%Id()

 Set LogFinalizar = ##class(Treinamento.Data.LogMensagem).Finalizar(IdLog, pStatusProcesso, pStatusCode)

 Set objConsultaLog = ##class(Treinamento.Data.LogMensagem).ConsultaLog(pStatus)
  For i=1:1:objConsultaLog.ListaLog.Count()
  {
     Set item = objConsultaLog.ListaLog.GetAt(i)

        Set jsonItem  = ##class(%DynamicObject).%New()
        Set jsonItem.Metodo = item.Metodo
        Set jsonItem.Classe = item.Classe
        Set jsonItem.Inicio = item.Inicio
        Set jsonItem.Fim = item.Fim
        Set jsonItem.Status = item.Status
        Set jsonItem.StatusProcesso = item.StatusProcesso  
        Do jsonArray.%Push(jsonItem)      
    
   } 
   Write !, "Retorno do Json : ", ! 
   Write jsonArray.%ToJSON(), !!

 Set jsonLogUnico = ##class(Treinamento.Data.LogMensagem).BuscarLogPorIdJSON(IdLog)    
    Write !,"=== [JSON] LOG ÚNICO CRIADO ===",!
    Write jsonLogUnico.%ToJSON(),!!       
    //teste 
    Set jsonPaginado = ##class(Treinamento.Data.LogMensagem).ConsultaLogPaginacaoJSON(pStatus, 1, pPageSize, pDataFim)
     Write "=== [JSON] CONSULTA PAGINADA ===",!
    Write jsonPaginado.%ToJSON(),!!

 For i=1:1:objConsultaLog.ListaLog.Count()
  {
    Set item = objConsultaLog.ListaLog.GetAt(i)
    Write "Item ", i, ! 
    Write "Metodo ....: " , item.Metodo, !
    Write "Classe ....: " , item.Classe, !
    Write "Inicio ....: " , item.Inicio, !
    Write "Fim ....: " , item.Fim, !
    Write "Status ....: " , item.Status, !
    Write "StatusProcesso ....:" , item.StatusProcesso, !!
    
 } 

 Set objLogPaginado = ##class(Treinamento.Data.LogMensagem).ConsultaLogPaginacao(pStatus, pLastId, pPageSize, pDataFim)

    For i=1:1:objLogPaginado.ListaLog.Count()
    {
        Set item = objLogPaginado.ListaLog.GetAt(i)       
        Write " ID : ", item.ID, " | Metodo : ", item.Metodo, " | Classe : ", item.Classe, "| Status : ", item.Status, !     
       
        Write ! 
    }

    