ROUTINE CriarLogMensgem

 
 Set pDataInicio = ##class(%UTC).NowLocal()
 Set pStatus = 0
 Set pClasse = "LogMensagem"
 Set pMetodo = "LogMetodo"
 Set pStatusProcesso = "Processo realizado com sucesso!" 
 Set pStatusCode = "1"
 Set pPageSize = 10
 Set pDataFim = $ZDateTime($HOROLOG,4)
 set pLastId = 1
  
 
 Set LogMensagemCriar = ##class(Treinamento.Data.LogMensagem).CriarEntrada("pMetodo", "pClasse")
 Set IdLog  = LogMensagemCriar.%Id()

 Set LogFinalizar = ##class(Treinamento.Data.LogMensagem).Finalizar(IdLog, pStatusProcesso, pStatusCode)

 Set objConsultaLog = ##class(Treinamento.Data.LogMensagem).ConsultaLog(pStatus)

 For i=1:1:objConsultaLog.ListaLog.Count()
  {
    Set item = objConsultaLog.ListaLog.GetAt(i)
    Write "Item ", i, ! 
    Write "Metodo ....: " , item.Metodo, !
    Write "Classe ....: " , item.Classe, !
    Write "Inicio ....: " , item.Inicio, !
    Write "Fim ....: " , item.Fim, !
    Write "Status ....: " , item.Status, !
    Write "StatusProcesso ....:" , item.StatusProcesso, !!
    
 } 

 
 Set objLogPaginado = ##class(Treinamento.Data.LogMensagem).ConsultaLogPaginacao(pStatus, pLastId, pPageSize, pDataFim)

    For i=1:1:objLogPaginado.ListaLog.Count()
    {
        Set item = objLogPaginado.ListaLog.GetAt(i)       
        Write " ID : ", item.ID, " | Metodo : ", item.Metodo, " | Classe : ", item.Classe, "| Status : ", item.Status, !     
       
        Write ! 
    }